In [3]:
import os
import pandas as pd

In [4]:
df = pd.read_csv("../data/pricing_data.csv",index_col='Column 1').reset_index()

In [5]:
df.columns,len(df.columns)

(Index(['Column 1', 's_title_diy', 's_description_diy', 's_currency_diy',
        's_original_price_diy', 's_primary_image_diy', 's_link_diy',
        's_vendor_diy', 's_metric_type_diy', 's_metric_type_unit_diy',
        's_metric_value_diy', 's_price_value_diy', 's_title_competitor',
        's_description_competitor', 's_currency_competitor',
        's_original_price_competitor', 's_primary_image_competitor',
        's_link_competitor', 's_vendor_competitor', 's_metric_type_competitor',
        's_metric_type_unit_competitor', 's_metric_value_competitor',
        's_price_value_competitor', 'product_id_diy', 'title_similarity',
        'matching_score', 'image_similarity', 's_brand_diy',
        's_brand_competitor', 's_scent_diy', 's_scent_competitor',
        'scent_match', 'exact_match', 'title', 'segment', 'collection',
        'category', 'product_type', 'competitor_is_diy_product',
        'competitor_is_diy_vendor', 'brand_match', 's_has_count_diy',
        's_count_value_diy', 's_count_unit_diy', 's_has_weight_diy',
        's_weight_value_diy', 's_weight_unit_diy', 's_has_volume_diy',
        's_volume_value_diy', 's_volume_unit_diy',
        's_price_per_unit_weight_diy', 's_price_per_unit_liquid_diy',
        's_price_per_unit_unit_diy', 's_price_per_unit_combined_diy',
        's_price_diy', 's_has_count_competitor', 's_count_value_competitor',
        's_count_unit_competitor', 's_has_weight_competitor',
        's_weight_value_competitor', 's_weight_unit_competitor',
        's_has_volume_competitor', 's_volume_value_competitor',
        's_volume_unit_competitor', 's_price_per_unit_weight_competitor',
        's_price_per_unit_liquid_competitor',
        's_price_per_unit_unit_competitor',
        's_price_per_unit_combined_competitor', 's_price_competitor',
        'price_index', 'normalised_price_index',
        's_price_per_unit_combined_diy_upper',
        's_price_per_unit_combined_diy_lower', 'selected_competitor_products',
        'consistent_unit_metric', 'final_unit', 'Unnamed: 76'],
       dtype='str'),
 77)

In [ ]:
df[['s_original_price_diy','s_original_price_competitor','s_price_competitor','price_index']]

,s_original_price_diy,s_original_price_competitor,s_price_competitor,price_index
4995,1.8,2.29,0.0229,0.786026
4996,1.8,7.90,0.0790,0.227848
4997,1.8,3.00,0.0300,0.600000
4998,1.8,5.90,0.0590,0.305085
4999,1.8,12.90,0.1290,0.139535
5000,1.8,12.00,0.1200,0.150000
5001,1.8,1.62,0.0162,1.111111
5002,1.8,3.28,0.0328,0.548780
5003,1.8,15.90,0.1590,0.113208
5004,1.8,9.99,0.0999,0.180180
5005,1.8,2.99,0.0299,0.602007
5006,1.8,1.90,0.0190,0.947368
5007,1.8,6.99,0.0699,0.257511
5008,1.8,1.89,0.0189,0.952381
5009,1.8,7.15,0.0715,0.251748
5010,1.8,3.19,0.0319,0.564263
5011,1.8,0.80,0.0080,2.250000
5012,1.8,4.90,0.0490,0.367347
5013,1.8,2.00,0.0200,0.900000
5014,1.8,0.55,0.0055,3.272727
5015,1.8,6.05,0.0605,0.297521
5016,1.8,4.50,0.0450,0.400000
5017,1.8,2.50,0.0250,0.720000
5018,1.8,4.80,0.0480,0.375000
5019,1.8,3.94,0.0394,0.456853
5020,1.8,2.90,0.0290,0.620690
5021,1.8,1.99,0.0199,0.904523

In [34]:
temp_df = df[['s_original_price_diy','s_original_price_competitor','s_price_competitor','price_index']].loc[df['product_id_diy']==7810243985584]

In [35]:
temp_df['cal_price_index']=temp_df['s_original_price_diy']/temp_df['s_original_price_competitor']

In [39]:
temp_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27 entries, 4995 to 5021
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   s_original_price_diy         27 non-null     float64
 1   s_original_price_competitor  27 non-null     float64
 2   s_price_competitor           27 non-null     float64
 3   price_index                  27 non-null     float64
 4   cal_price_index              27 non-null     float64
dtypes: float64(5)
memory usage: 1.2 KB

In [40]:
temp_df

,s_original_price_diy,s_original_price_competitor,s_price_competitor,price_index,cal_price_index
4995,1.8,2.29,0.0229,0.786026,0.786026
4996,1.8,7.90,0.0790,0.227848,0.227848
4997,1.8,3.00,0.0300,0.600000,0.600000
4998,1.8,5.90,0.0590,0.305085,0.305085
4999,1.8,12.90,0.1290,0.139535,0.139535
5000,1.8,12.00,0.1200,0.150000,0.150000
5001,1.8,1.62,0.0162,1.111111,1.111111
5002,1.8,3.28,0.0328,0.548780,0.548780
5003,1.8,15.90,0.1590,0.113208,0.113208
5004,1.8,9.99,0.0999,0.180180,0.180180
5005,1.8,2.99,0.0299,0.602007,0.602007
5006,1.8,1.90,0.0190,0.947368,0.947368
5007,1.8,6.99,0.0699,0.257511,0.257511
5008,1.8,1.89,0.0189,0.952381,0.952381
5009,1.8,7.15,0.0715,0.251748,0.251748
5010,1.8,3.19,0.0319,0.564263,0.564263
5011,1.8,0.80,0.0080,2.250000,2.250000
5012,1.8,4.90,0.0490,0.367347,0.367347
5013,1.8,2.00,0.0200,0.900000,0.900000
5014,1.8,0.55,0.0055,3.272727,3.272727
5015,1.8,6.05,0.0605,0.297521,0.297521
5016,1.8,4.50,0.0450,0.400000,0.400000
5017,1.8,2.50,0.0250,0.720000,0.720000
5018,1.8,4.80,0.0480,0.375000,0.375000
5019,1.8,3.94,0.0394,0.456853,0.456853
5020,1.8,2.90,0.0290,0.620690,0.620690
5021,1.8,1.99,0.0199,0.904523,0.904523

In [7]:
df['s_price_diy'].isna().sum()

np.int64(0)

In [15]:
df.shape

(5186, 77)

In [ ]:
df.pr.unique()

<StringArray>
[                                                 'Easy Spin Mop 360 - Stainless Steel Handle & Basket with Plastic Bucket (Includes Free Mop Head)',
                                                                                         'Super Spin Mop Stainless Steel Basket + 2 Mop Heads - Red',
                                                                                                   'spin magic mop+cleaner bucket+2 mop heads(free)',
 'Spin Mop & Bucket System With Dual Compartment (Clean & Dirty Water Separation), 360° Swivel Self-Cleaning Mop Head, Built-In Scrubbing Brush & 2',
                                                                                                         'Spin Bucket Mop Set Me Living Taiku Green',
                                                     '[READYSTOCK] Wheels & Stainless Steel Basket with Easy Spin Mop 360° (2 Mop Heads) mop Lantai',
                                                                                                '360° Spin Rotating MOP & Bucket | Dennyshop UK Red',
                                                                                'Spin Mop Cleaning System,mop And Bucket With Wringer Set For Floor',
                                                                                                             'Spin Bucket Mop Set Acco Ds-307 Beige',
                                                        'Spin Mop And Bucket Set Free Hand Wash Mop Flat Mop Single Barrel Flat Floating Rotaty Mop',
 ...
                                                                                                             'Sogo Ubat Gegat 80G Naphthalene Balls',
                                                                                                          'Sogo Ubat Gegat 80g Naphthalene Balls 臭丸',
                                                                            'Malaysia Ready StockUbat Gegat / Moth Balls / Naphthalene Balls 80g 臭丸',
                                       'Ready Stock80g/200g Naphthalene Moth Ball Mothball Mothballs Wardrobe Clothes Ubat Gegat Lipas Pest Control',
                                                              'Ready-Stock Ready Stock Naphthalene balls 80g/100g/150g/200g Ubat Gegat Moth Ball 臭丸',
                                                                                                                    'Ubat Gegat 80G ( 1pack ) White',
                                             'Jooly Ubat Gegat 80g - Pembasmi & Penghalau Lipas, Anai-Anai, Kutu, Gegat, Cengkerik | Pest Repellent',
                                                                                               '(Mr. Diy) Powerful Moth Repellent Ubat Gegat (120G)',
                                                                                                                     'Tiger Powerful Ubat Gegat 80g',
                                                                       'Pack Ready Stock Ubat Gegat /Freshener 80g /臭丸 Good Quality Products Rm1.49']
Length: 4012, dtype: str

In [ ]:
df.s_currency_competitor.unique()

In [19]:
df.category.unique()

<StringArray>
[         'Mops & Mop Accessories',                'Trash & Dustbins',
                  'Air Fresheners',          'Storage & Fabric Items',
                'Diffusers & Oils',         'Sponges & Scouring Pads',
          'Multi-Purpose Cleaners',        'Cloths, Towels & Dusters',
               'Brooms & Dustpans',                          'Gloves',
                    'Garbage Bags',         'Insecticides & Aerosols',
                 'Toilet Cleaners',                'Cleaning Brushes',
 'Fabric Softeners & Conditioners',                'Kitchen Cleaners',
          'Tissues & Paper Towels',          'Bleach & Disinfectants',
            'Detergents & Powders',            'Dishwashing Products',
             'Laundry Nets & Bags',            'Cleaning Accessories',
                           'Wipes',         'Washing Machine Cleaner',
           'Candles & Room Sprays',              'Traps & Repellents',
             'Laundry Accessories',             'Moth & Odor Control']
Length: 28, dtype: str

In [16]:
df.segment.unique()

<StringArray>
[           'Home Cleaning & Tools',       'Waste & Storage Management',
             'Air Care & Fragrance', 'Home Accessories & Miscellaneous',
   'Household Chemicals & Cleaners', 'Protective & Disposable Supplies',
                     'Pest Control',            'Laundry & Fabric Care']
Length: 8, dtype: str

In [17]:
df.collection.unique()

<StringArray>
[                 'Floor Cleaning',                  'Waste Disposal',
                  'Air Freshening',          'Small Home Accessories',
         'Aromatherapy & Ambience',    'Scrubbing & Surface Cleaning',
 'Surface & Multipurpose Cleaners',                'Hygiene & Gloves',
         'Insect & Rodent Control',        'Sanitary & Dish Cleaning',
             'Fabric Conditioning',                  'Wiping & Paper',
              'Washing Essentials',                'Laundry Handling',
                   'Disinfectants',          'Odor & Moth Prevention']
Length: 16, dtype: str

In [18]:
df.product_type.unique()

<StringArray>
[              'Mop Bucket Set',                    'Spray Mop',
          'Push Button Dustbin',           'Round Step Dustbin',
              'Automatic Spray',             'Laptop Briefcase',
            'Aromatic Diffuser',              'Mesh Organizers',
                'Pedal Dustbin',                     'Flat Mop',
                   'Roller Mop',         'Multi-Purpose Sponge',
                    'Twist Mop',             'Bathroom Cleaner',
         'Multi-Action Cleaner',  'Cleaning Coral Fabric Cloth',
                 'Mini Dustbin',               'Microfiber Mop',
                        'Broom',                  'Scented Gel',
               'Nitrile Gloves',             'HDPE Garbage Bag',
     'Eco-Friendly Garbage Bag',        'Twin Roll Garbage Bag',
         'Metal Mesh Trash Bin', 'Mosquito & Cockroach Aerosol',
           'Toilet Gel Cleaner',          'Air Refresher Spray',
                 'Toilet Brush',                'Fragrance Oil',
       'Fabric Refresher Spray',                      'Dustpan',
              'Kitchen Cleaner',           'Toilet Roll Tissue',
 'Anti-Bacterial Spray Cleaner', 'Mop Refill / Replacement Pad',
                'Floor Cleaner',            'Microfiber Duster',
        'Mini Roll Garbage Bag',     'Laundry Detergent Powder',
          'Polyethylene Gloves',       'Car Air Freshener Clip',
        'Broom and Dustpan Set',            'Dishwashing Paste',
       'Fabric Softener Refill',            'Laundry Gel Beads',
                   'Scrub Dots',           'Kitchen Towel Roll',
             'Hand Scrub Brush',          'Multi-purpose Brush',
                'Facial Tissue',        'Fine Mesh Laundry Net',
           'Dishwashing Liquid',           'Tube & Spout Brush',
                       'Bleach',      'Dishwashing Refill Pack',
                  'Lint Roller',    'Antibacterial Floor Wipes',
       'Mini Desktop Broom Set',      'Washing Machine Cleaner',
      'Dual-Sided Scouring Pad',                   'Room Spray',
             'Microfiber Cloth',           'Lint Roller Refill',
        'Reusable Lint Remover',  'Cleaning Magic Sponge White',
              'Mouse Glue Trap',     'Baby Bottle Cleaning Set',
            'Kitchen Wet Wipes',             'Household Gloves',
                 'Laundry Ball',                 'Trash Basket',
                  'Work Gloves',                'Flush Tablets',
          'Toilet Blue Tablets',                  'Laundry Bag',
             'Soft Pack Tissue',                     'Mothball',
               'Feather Duster',      'Cylindrical Laundry Net',
     'Microfiber Kitchen Towel',                   'Ubat Gegat',
           'Rubber Palm Gloves',          'Scented Garbage Bag',
          'Coconut Fiber Brush',       'Kuat Harimau Detergent',
         'Disposable Wet Wipes',        'Hanging Air Freshener',
           'Dishwashing Sponge',     'Furniture Cleaning Wipes',
                'Laundry Brush',                 'Bottle Brush',
       'Dishwashing Net Sponge',  'Dehumidifying Fragrance Bag',
                   'Hand Towel',               'Moth Repellent',
          'Steel Scouring Ball']
Length: 97, dtype: str